---

- name: download tomcat version
  get_url: url=http://apache.mirrors.ionfish.org/tomcat/tomcat-8/v8.0.47/bin/apache-tomcat-8.0.47.tar.gz dest=/opt/

- name: chect is it already extracted or not
  stat:
    path: /opt/tomcat/webapps
  register: result

- name: extract tar file
  unarchive: src=/opt/apache-tomcat-8.0.47.tar.gz extra_opts="--strip-components=1" dest=/opt/tomcat remote_src=yes group=tomcat owner=tomcat
  when: result.stat.exists == false
  register: remove
  ignore_errors: true

- name: remove unwanted folders
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/opt/tomcat/webapps/ROOT"
    - "/opt/tomcat/webapps/docs"
    - "/opt/tomcat/webapps/examples"
    - "/opt/tomcat/webapps/manager"
    - "/opt/tomcat/webapps/host-manager"
  when: remove.changed

