---
#- name: downloading and deploying artifacts from nexus
#  maven_artifact: group_id={{ group_id }} artifact_id={{ artifact_id }} repository_url={{ nexus_repo }} username={{ nexus_user }} password={{ nexus_pass }} dest={{ tomcat_dest }} version={{ version }} extension=war

- name: stop tomcat
  service: name=tomcat state=stopped

- name: downloading and deploying from nexus
  maven_artifact: group_id=com.company artifact_id=newprojrct repository_url=http:{{ repo_url }} username=user password=xxxxxxx dest=/your/dest/dir version=latest extension=war

- name: restart tomcat
  service: name=tomcat state=restarted

