---
# tasks file for truedeploy.mariadb1

- name: create a new data base
  mysql_db: name={{ db_name }} state=present collation=utf8_unicode_ci

- name: create db user and password
  mysql_user: name={{ db_user }} password={{ db_password }} priv=*.*:ALL


- name: restart mariadb
  service: name=mariadb state=restarted

